### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Woolyenough** [VidTu/In-Game-Account-Switcher#12]
### Describe the bug

Attempting to add a Microsoft account returns an error.

### To Reproduce

1. Launch the game with the mod installed.
2. Try adding a Microsoft account.

![You will receive this error.](https://user-images.githubusercontent.com/99221540/166516784-9d7ae58e-ce60-4341-a8a7-5de134af94f7.png)
 

### Minecraft Version

Fabric 1.16.5

### Checklist

- [X] I'm using the latest [mod version](https://modrinth.com/mod/in-game-account-switcher)
- [X] I'm using the latest [Forge](https://files.minecraftforge.net) or [Fabric](https://fabricmc.net/use/)/[Fabric-API](https://modrinth.com/mod/fabric-api) for my Minecraft version

**Comment by VidTu** [comment]
See [this](https://github.com/The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher/issues/53) (I'm already in progress for fixing this on older Java 8 versions, but you need to use newer Java 8 build for now)
