### ISSUE TITLE
[Bug] Mojang Accounts dupe?

### ISSUE THREAD

**Issue by rory233** [VidTu/In-Game-Account-Switcher#6]
### Describe the bug

My mojang accounts constantly duplicate whenever I open my game. I try logging into these accounts and they don't let me use them and give me an error message. Microsoft accounts seem to work fine though and never do this. Deleting them and readding the accounts fixes it until I open my game again. 

### To Reproduce

1. Open game
2. Usually they've instantly reappeared even if I've deleted them before closing the game, but sometimes I have to join a server or play for a little bit before they show up again.
3. I can't use them and get this error
![image](https://user-images.githubusercontent.com/100042436/154813714-47dda52e-1043-4616-b338-cb82c33e1e17.png)

### Minecraft Version

Fabric 1.15.2

### Logs/Screenshots/Videos

https://gyazo.com/f256082fa7a3ed7716ced116f709b7b5 https://gyazo.com/bc765cf7796ca3a21243226f8ec6c8df

### Checklist

- [X] I'm using the latest [mod version](https://modrinth.com/mod/in-game-account-switcher)
- [X] I'm using the latest [Forge](https://files.minecraftforge.net) or [Fabric](https://fabricmc.net/use/)/[Fabric-API](https://modrinth.com/mod/fabric-api) for my Minecraft version

**Comment by VidTu** [comment]
Does it log errors or conversion-like messages?

**Comment by rory233** [comment]
No errors or anything, it just usually doesn't let me login to the accounts with the ias.mojangauth thing. Not really sure what conversion like messages are though srry

**Comment by VidTu** [comment]
Should be fixed in 7.2.0.
